remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Brayan steven 
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/proycectito.appspot.com/o/foto-fotor-2023092110289.png?alt=media&token=0785f215-9a34-415e-8135-53d3cd524928

